# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d27dedf6-2a32-4cd3-b739-d5f53a5f45a3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6071-F05A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp59s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Set up GPU correctly.
  # Details: https://wiki.nixos.org/wiki/NVIDIA

  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "modesetting" "nvidia" ];
  hardware.nvidia.open = false;

  # Enable PRIME.
  # This is pretty much necessary for systems with both iGPU and dGPU.
  # By looking at lspci, we can see the PCI numbers:
  # ```sh
  # $ lspci -k | grep -EA3 'VGA|3D|Display'
  # 00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
  #         DeviceName:  Onboard IGD
  #         Subsystem: Dell Device 0825
  #         Kernel driver in use: i915
  # --
  # 01:00.0 VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)
  #         Subsystem: Dell Device 0825
  #         Kernel driver in use: nouveau
  #         Kernel modules: nvidiafb, nouveau
  # ```
  hardware.nvidia.prime = {
    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:1:0:0";
    # Enable Offload mode.
    # Requires videoDrivers to have both "modesettings" (Intel iGPU driver) and "nvidia" (NVIDIA dGPU driver)
    offload = {
      enable = true;
      enableOffloadCmd = true; # Prepend any shell expression with `nvidia-offload` to use the dGPU
    };
  };
}
