[package]
name = "mv-nix"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
git2 = "0.20.2"
pathdiff = "0.2.3"
rnix = "0.12.0"
rowan = "0.16.1"
walkdir = "2.5.0"
