[package]
name = "cp-discord"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cp-model.workspace = true

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
twilight-http.workspace = true
twilight-model.workspace = true

[dev-dependencies]
cp-core.workspace = true
serde_json.workspace = true
tempfile = "3"
tokio.workspace = true
wiremock.workspace = true
